### ISSUE TITLE
Зачем отдельный поток с movePlayer()?

### ISSUE THREAD

**Issue by dimalit** [dimasheva1/Maze#1]
Почему нельзя просто в обработчиках нажатия клавиш делать goLeft()/goRight() и т.д.?

**Comment by dimasheva1** [comment]
Потому что этот поток отвечает за плавное движение моего игрока. Без него он будет дергаться

**Comment by dimasheva1** [comment]
Подумал о том чтобы убрать его в класс Map, но проблема с тем что в цикле repaint панели.

**Comment by dimalit** [comment]
А, это анимация. Тогда OK.
