### ISSUE TITLE
Почему Game.Map - static?

### ISSUE THREAD

**Issue by dimalit** [dimasheva1/Maze#2]
Разве нельзя создать две "игры" на двух разных "картах"?

**Comment by dimasheva1** [comment]
По сути у меня нельзя создать две игры, только по очереди

**Comment by dimalit** [comment]
Тогда в этом классе все должно быть static - и нигде не создаваться ни одного объекта этого класса.
(или использовать паттерн singleton, но тогда как раз все станет не-static)

**Comment by dimasheva1** [comment]
Map уже не используется как статик. Когда отделил логику и GUI, все стало с мапом ясно
