### ISSUE TITLE
Отделить логику и GUI

### ISSUE THREAD

**Issue by dimalit** [dimasheva1/Maze#3]
Класс Map хранит карту лабиринта. Лучше разделить его на два - тот, который хранит карту и тот, который ее показывает (представь, что у игры появилась web-версия - надо, чтобы при этом не нужно было переписывать существующие классы, а лишь добавлять новые).

**Comment by dimasheva1** [comment]
Один класс который хранит, а во втором, тоесть панели, передать обьект этого класса? И уже оттуда читать?

**Comment by dimasheva1** [comment]
Выполено
